
strictness: high

max-line-length: 120

member-warnings: true

doc-warnings: false

test-warnings: false

pylint:
  options:
    init-import: true
    dummy-variables-rgx: _$|dummy|___

  disable:
    # getargspec
    - deprecated-method

    # optparse
    - deprecated-module

    - bare-except
    - broad-except
    - invalid-name
    - multiple-statements
    - no-self-use
    - protected-access
    - redefined-builtin
    - too-many-arguments
    - too-many-branches
    - too-many-instance-attributes
    - too-many-lines
    - too-many-locals
    - too-many-return-statements
    - too-many-statements
    - unused-argument
    - unused-wildcard-import
    - wildcard-import

pyflakes:
  disable:
    - F999
    - F401
    - F403
    - F841

mccabe:
  run: false

