
name: REL

on:
  push:
    tags: ["v[0-9]*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Build tarball
        id: build
        run: |
          python3 setup.py sdist
          PACKAGE=$(python3 setup.py --name)
          VERSION=$(python3 setup.py --version)
          TGZ="${PACKAGE}-${VERSION}.tar.gz"
          test "${{github.ref}}" = "refs/tags/v${VERSION}" || { echo "ERR: tag mismatch"; exit 1; }
          test -f "dist/${TGZ}" || { echo "ERR: sdist failed"; exit 1; }
          echo "::set-env name=PACKAGE::${PACKAGE}"
          echo "::set-env name=VERSION::${VERSION}"
          echo "::set-env name=TGZ::${TGZ}"

      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.event.repository.name}} v${{env.EXT_VERSION}}
          body_path: docs/notes/v${{env.EXT_VERSION}}.md
          draft: false
          prerelease: false

      - name: Upload source
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.release.outputs.upload_url}}
          asset_path: dist/${{env.TGZ}}
          asset_name: ${{env.TGZ}}
          asset_content_type: application/x-gzip

