#
# https://docs.github.com/en/actions/reference
# https://github.com/actions
#

name: REL

on:
  push:
    tags: ["v[0-9]*"]

jobs:
  sdist:
    name: "Build source package"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {python-version: "3.8"}
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with: {name: "dist", path: "dist"}

  linux_wheels:
    name: "Wheel: manylinux2014"
    needs: [sdist]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with: {name: "dist", path: "sdist"}
      - uses: "docker://quay.io/pypa/manylinux2014_x86_64:latest"
        with: {entrypoint: "./.github/workflows/manylinux.sh"}
      - uses: "docker://quay.io/pypa/manylinux2014_i686:latest"
        with: {entrypoint: "./.github/workflows/manylinux.sh"}
      - uses: actions/upload-artifact@v2
        with: {name: "dist", path: "dist"}

  other_wheels:
    name: "Wheel: ${{matrix.sys.name}}-${{matrix.sys.pyarch}}-${{matrix.pyver}}"
    needs: [sdist]
    runs-on: ${{matrix.sys.os}}
    strategy:
      matrix:
        sys:
          - {os: "macos-10.15", name: "MacOS 10.15", pyarch: "x64", opts: "--build-option --py-limited-api=cp36", repack: false}
          - {os: "windows-2019", name: "Windows 2019", pyarch: "x86", opts: "", repack: true}
          - {os: "windows-2019", name: "Windows 2019", pyarch: "x64", opts: "", repack: true}
        pyver: ["3.6"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {architecture: "${{matrix.sys.pyarch}}", python-version: "${{matrix.pyver}}"}
      - uses: actions/download-artifact@v2
        with: {name: "dist", path: "sdist"}
      - name: "Build"
        shell: bash
        run: |
          pip install --disable-pip-version-check -U wheel
          pip wheel --disable-pip-version-check ${{matrix.sys.opts}} -w dist sdist/*.tar.gz
          ls -l dist
      - name: "Repack"
        if: ${{matrix.sys.repack}}
        shell: bash
        run: |
          mv dist dist2
          python .github/workflows/win32abi3.py -d dist dist2/*.whl
          ls -l dist
      - uses: actions/upload-artifact@v2
        with: {name: "dist", path: "dist"}

  publish:
    name: "Publish"
    runs-on: ubuntu-20.04
    needs: [linux_wheels, other_wheels]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {python-version: "3.8"}
      - uses: actions/download-artifact@v2
        with: {name: "dist", path: "dist"}
      - name: "Prepare"
        run: |
          PACKAGE=$(python setup.py --name)
          VERSION=$(python setup.py --version)
          TGZ="${PACKAGE}-${VERSION}.tar.gz"
          # default - gh:release, pypi
          # PRERELEASE -  gh:prerelease, pypi
          # DRAFT - gh:draft,prerelease, testpypi
          PRERELEASE="false"
          DRAFT="false"
          if echo "${VERSION}" | grep -qE '(a|b|rc)'; then PRERELEASE="true"; fi
          if echo "${VERSION}" | grep -qE '(dev)'; then DRAFT="true"; PRERELEASE="true"; fi
          test "${{github.ref}}" = "refs/tags/v${VERSION}" || { echo "ERR: tag mismatch"; exit 1; }
          test -f "dist/${TGZ}" || { echo "ERR: sdist failed"; exit 1; }
          echo "PACKAGE=${PACKAGE}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TGZ=${TGZ}" >> $GITHUB_ENV
          echo "PRERELEASE=${PRERELEASE}" >> $GITHUB_ENV
          echo "DRAFT=${DRAFT}" >> $GITHUB_ENV
          sudo -nH apt-get -u -y install pandoc
          pandoc --version
          mkdir -p tmp
          make -s shownote > tmp/note.md
          cat tmp/note.md

      - name: "Create release"
        id: github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{env.PACKAGE}} v${{env.VERSION}}
          body_path: tmp/note.md
          prerelease: ${{env.PRERELEASE}}
          draft: ${{env.DRAFT}}

      - name: "Upload to Github"
        id: github_upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.github_release.outputs.upload_url}}
          asset_path: dist/${{env.TGZ}}
          asset_name: ${{env.TGZ}}
          asset_content_type: application/x-gzip

      - name: "Upload to PYPI"
        id: pypi_upload
        env:
          PYPI_TOKEN: ${{secrets.PYPI_TOKEN}}
          PYPI_TEST_TOKEN: ${{secrets.PYPI_TEST_TOKEN}}
        run: |
          pip install --disable-pip-version-check -U twine
          ls -l dist
          if test "${DRAFT}" = "false"; then
            python -m twine upload -u __token__ -p ${PYPI_TOKEN} \
              --repository pypi --disable-progress-bar dist/*
          else
            python -m twine upload -u __token__ -p ${PYPI_TEST_TOKEN} \
              --repository testpypi --disable-progress-bar dist/*
          fi

